# Generated by Django 3.2.6 on 2021-08-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('donation_level', models.CharField(max_length=50)),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
    ]
