# Generated by Django 3.2.6 on 2021-08-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation_submission',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
    ]
