# Generated by Django 3.2.6 on 2021-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_submission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_submission',
            name='donation_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation_submission',
            name='recurring',
            field=models.CharField(default='once', max_length=100),
        ),
    ]
