# Generated by Django 3.2.7 on 2021-10-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20210901_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='merch_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=400)),
                ('address_2', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=15)),
                ('green_mugs', models.IntegerField()),
                ('white_mugs', models.IntegerField()),
                ('blackss_medium', models.IntegerField()),
                ('blackss_large', models.IntegerField()),
                ('blackss_xl', models.IntegerField()),
                ('blackss_xxl', models.IntegerField()),
                ('greyss_medium', models.IntegerField()),
                ('greyss_large', models.IntegerField()),
                ('greyss_xl', models.IntegerField()),
                ('greyss_xxl', models.IntegerField()),
                ('whitess_medium', models.IntegerField()),
                ('whitess_large', models.IntegerField()),
                ('whitess_xl', models.IntegerField()),
                ('whitess_xxl', models.IntegerField()),
                ('blackls_medium', models.IntegerField()),
                ('blackls_large', models.IntegerField()),
                ('blackls_xl', models.IntegerField()),
                ('blackls_xxl', models.IntegerField()),
                ('whitels_medium', models.IntegerField()),
                ('whitels_large', models.IntegerField()),
                ('whitels_xl', models.IntegerField()),
                ('whitels_xxl', models.IntegerField()),
            ],
        ),
    ]
